---
name: my-plan-project
description: Repository-specific operating knowledge for My Plan Workers in {{repositoryName}}. Loaded by path from a Worker handoff, not by model selection.
---

# {{repositoryName}}

Navigator. Every fact here is verified from this repository, never assumed from
its stack's conventions. Structured facts live in `project.json`; this file says
where to look and what to be careful about.

Generated by My Plan and updated only by My Plan. Existing agent instructions,
custom skills, and canonical documentation are left intact.

## Architecture Memory

Read `{{architectureMemoryPath}}` completely before planning, implementing,
auditing, reviewing, testing, or delivering. It is the current architecture; this
file is only the entry point.

## Stack

{{stackSummary}}

Package manager: `{{packageManager}}`. Use it. Do not introduce another.

## Validation

Run these before claiming anything is done. Exact commands, from `project.json`:

{{validationCommands}}

## Boundaries

{{moduleBoundaries}}

Where a change in one module requires a matching change in another, say so here.

## Conventions that are not obvious from the code

{{conventions}}

Only conventions a competent stranger would get wrong. Not a style guide.

## Pitfalls

{{pitfalls}}

Proven failures, each with the evidence that proved it. Not hypothetical warnings.

## References

The `references/` directory does not exist by default. It is created only when
stack rules, validation, tooling, architecture, or review guidance cannot be
represented by an existing canonical repository document or the Architecture
Memory. Prefer linking the repository's own documentation over copying it here.

{{references}}
